# 보스턴 집값 Data Lodaing

In [1]:
import pandas as pd  # 라이브러리 호출

In [2]:
data_url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data' # data URL
df_data = pd.read_csv(data_url, sep='\s+', header=None) # csv 타입 데이터 로드 , 구분자는 빈공간으로 지정하고, 컬럼은 없음

In [3]:
df_data.head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [4]:
df_data.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], dtype='int64')

In [5]:
df_data.columns = ['CRIM', 'ZN', 'INDOS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV' ]

In [6]:
df_data.columns

Index(['CRIM', 'ZN', 'INDOS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [7]:
df_data.head()

CRIM    ZN  INDOS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [8]:
df_data

CRIM    ZN  INDOS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]


# numpy 계산해 보기



In [9]:
import numpy as np  # Numpy 라이브러리 호출

In [10]:
weight_vector = np.array([[1], [1], [1]]) # Weight Vector

In [11]:
weight_vector

array([[1],
       [1],
       [1]])

In [12]:
x_vector = np.array([[3], [4], [5]]) # X Vector

In [13]:
x_vector

array([[3],
       [4],
       [5]])

In [14]:
weight_vector.shape

(3, 1)

In [15]:
x_vector.shape

(3, 1)

In [16]:
x_vector.ndim

2

In [17]:
weight_vector.T

array([[1, 1, 1]])

In [18]:
weight_vector.T.dot(x_vector)  # 1 * 3 + 1 * 4 + 1* 5 = 12

array([[12]])

# 보스턴 집값 데이터 조작하기

In [19]:
df_data.head()

CRIM    ZN  INDOS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [20]:
df_data['weight_0'] = 1

In [21]:
df_data.head()

CRIM    ZN  INDOS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  weight_0  
0     15.3  396.90   4.98  24.0         1  
1     17.8  396.90   9.14  21.6         1  
2     17.8  392.83   4.03  34.7         1  
3     18.7  394.63   2.94  33.4         1  
4     18.7  396.90   5.33  36.2         1

In [22]:
df_data = df_data.drop('MEDV',axis=1)

In [23]:
df_data.head()

CRIM    ZN  INDOS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  weight_0  
0     15.3  396.90   4.98         1  
1     17.8  396.90   9.14         1  
2     17.8  392.83   4.03         1  
3     18.7  394.63   2.94         1  
4     18.7  396.90   5.33         1

In [24]:
df_data.values

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        1.0000e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        1.0000e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        1.0000e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        1.0000e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        1.0000e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.0000e+00]])

In [25]:
df_data.values[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00, 1.000e+00])

# Datafram --> Numpy, 곱셈 연산

In [26]:
weight_vector = np.random.random_sample((14, 1))

In [27]:
weight_vector

array([[0.34559257],
       [0.32170389],
       [0.47187234],
       [0.77507286],
       [0.57160971],
       [0.23498139],
       [0.38730386],
       [0.74149547],
       [0.33646869],
       [0.86787699],
       [0.29084862],
       [0.97529655],
       [0.62999079],
       [0.20429502]])

In [28]:
df_matrix = df_data.to_numpy()  # dataframe을 numpy로 변경 

In [29]:
df_matrix.shape

(506, 14)

In [31]:
weight_vector.shape

(14, 1)

In [32]:
df_matrix.dot(weight_vector)

array([[ 689.1352259 ],
       [ 648.29771711],
       [ 634.39451736],
       [ 611.2343871 ],
       [ 618.25502925],
       [ 617.02894445],
       [ 709.27058098],
       [ 726.54369181],
       [ 724.82268548],
       [ 711.80851527],
       [ 722.76345061],
       [ 717.88407543],
       [ 695.56507848],
       [ 699.58522972],
       [ 693.0292681 ],
       [ 696.23369742],
       [ 676.12614125],
       [ 701.16118877],
       [ 586.01021253],
       [ 697.97254966],
       [ 701.30671031],
       [ 709.00944869],
       [ 717.46722576],
       [ 719.03700891],
       [ 714.46122119],
       [ 622.67157119],
       [ 695.18809372],
       [ 627.38838834],
       [ 706.32318575],
       [ 695.49862028],
       [ 685.07243417],
       [ 697.60445904],
       [ 559.15111665],
       [ 681.05197952],
       [ 575.54213543],
       [ 676.22180626],
       [ 655.81871876],
       [ 665.71906144],
       [ 658.81065833],
       [ 653.59119524],
       [ 649.88630741],
       [ 598.090

In [33]:
df_matrix.dot(weight_vector).shape

(506, 1)