# Numpy 호출

In [1]:
import numpy as np

# Array 생성

In [2]:
test_array = np.array(["1", "4", 5, 8], float)  # float 타입으로 자동 형 변환 
test_array

array([1., 4., 5., 8.])

In [3]:
type(test_array[3])

numpy.float64

In [4]:
test_array = np.array(["1", "4", 5, 8], np.float16)
test_array

array([1., 4., 5., 8.], dtype=float16)

In [5]:
test_array.dtype

dtype('float16')

In [6]:
test_array = np.array(["1", "4", 5, 8], np.int32)
test_array

array([1, 4, 5, 8])

In [7]:
test_array.dtype

dtype('int32')

In [8]:
test_array = np.array(["1", "4", 5, 8], np.str)
test_array

array(['1', '4', '5', '8'], dtype='<U1')

In [9]:
test_array.dtype

dtype('<U1')

In [10]:
test_array.shape

(4,)

# vector, matrix, tensor 

### array shape

In [11]:
vector = [1, 2, 3, 4]

In [12]:
np.array(vector, int).shape

(4,)

In [13]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]

In [14]:
np.array(matrix, int).shape

(3, 4)

In [15]:
tensor = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]

In [16]:
np.array(tensor, int).shape

(4, 3, 4)

In [17]:
np.array(tensor, int).ndim

3

In [18]:
np.array(tensor, int).size

48

# Handling Shape

## reshape

In [19]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix,int).shape

(2, 4)

In [20]:
np.array(test_matrix,int).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [21]:
np.array(test_matrix,int).reshape(8,).shape

(8,)

In [22]:
np.array(test_matrix,int).reshape(1,8)

array([[1, 2, 3, 4, 1, 2, 5, 8]])

In [23]:
np.array(test_matrix,int).reshape(1,8).shape

(1, 8)

In [24]:
np.array(test_matrix,int).shape

(2, 4)

In [25]:
np.array(test_matrix,int).reshape(2,-1).shape

(2, 4)

In [26]:
np.array(test_matrix,int).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [27]:
a = np.array(test_matrix,int).reshape(2,2,2)
a.size

8

In [28]:
a.shape

(2, 2, 2)

In [29]:
a.reshape(-1,4)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])