# Numpy - Indexing & Slicing

## indexing

In [1]:
import numpy as np

In [2]:
test_example = np.array([[1, 2, 3],[4.5, 5, 6]], dtype=int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
test_example[0][2]

3

In [4]:
test_example[0, 2]

3

In [5]:
test_example[0, 0] = 12 
test_example

array([[12,  2,  3],
       [ 4,  5,  6]])

In [6]:
test_example[0][0] = 5
test_example[0, 0]

5

## Slicing

In [7]:
test_example = np.array([
    [1, 2, 5, 8],
    [1, 2, 5, 8],
    [1, 2, 5, 8],
    [1, 2, 5, 8]], int)

In [8]:
test_example

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [9]:
test_example.shape

(4, 4)

In [10]:
test_example[0]

array([1, 2, 5, 8])

In [11]:
test_example[:3, 1:3]

array([[2, 5],
       [2, 5],
       [2, 5]])

In [12]:
test_example[:, 1:3]

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [13]:
test_example[1, :2]

array([1, 2])

In [14]:
test_example = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype=int)
test_example

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
test_example[:, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [16]:
test_example[1, 1:3]

array([7, 8])

In [17]:
test_example[1:3]

array([[ 6,  7,  8,  9, 10]])