# 3-6 numpy - operation functions

## axis 

In [1]:
import numpy as np

In [2]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
test_array.sum()

55

In [4]:
test_array.sum(dtype=np.float)

55.0

In [5]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
test_array.sum()

78

In [7]:
test_array.sum(axis=1)

array([10, 26, 42])

In [8]:
 test_array.sum(axis=0)

array([15, 18, 21, 24])

## mean , std , math fuction

In [9]:
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
test_array.mean()

6.5

In [11]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [12]:
test_array.std()

3.452052529534663

In [13]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [14]:
np.exp(test_array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [15]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

## vstack, hstack , concatenate

In [16]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [17]:
c = np.vstack((a, b))
c

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.hstack((a, b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [19]:
a = np.array([1, 2, 3]) # Vector

In [20]:
a.shape , a.ndim

((3,), 1)

In [21]:
a = np.array([[1, 2, 3]]) # matrix

In [22]:
a.shape , a.ndim

((1, 3), 2)

In [23]:
a = np.array([[1, 2, 3]])

In [24]:
b = np.array([[2, 3, 4]])

In [25]:
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [26]:
a = np.array([[1, 2],
             [3, 4]])

In [27]:
a.shape , a.ndim

((2, 2), 2)

In [28]:
b = np.array([[5, 6]])

In [29]:
b.shape, b.ndim

((1, 2), 2)

In [30]:
b.T

array([[5],
       [6]])

In [31]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])