# 3-8 numpy - comparisons

## All & Any

In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [4]:
np.any(a>5) ,  np.any(a<0)

(True, False)

In [5]:
np.all(a>5) , np.all(a<10)

(False, True)

## comparision operation

In [6]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [7]:
test_a == test_b

array([False, False, False])

In [8]:
(test_a > test_b).any()

True

In [9]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [10]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [11]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

In [12]:
a

array([1., 3., 0.])

In [13]:
a > 0 

array([ True,  True, False])

In [14]:
np.where(a > 0 , 3, 2)  # where (condition , True, False)

array([3, 3, 2])

In [15]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
a > 10

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [17]:
np.where(a > 10)   # condition만 주어지만 조건에 맞는 index 위치 반환

(array([6, 7, 8, 9], dtype=int64),)

In [18]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [19]:
np.isnan(a)

array([False,  True, False])

In [20]:
np.isfinite(a)

array([ True, False, False])

## argmax & argmin

In [21]:
a =  np.array([1,2,4,5,8,78,23,3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [22]:
np.argmax(a)

5

In [23]:
np.argmin(a)

0

In [24]:
a = np.array([
    [1,2,4,7],
    [9,88,6,45],
    [9,76,3,4]
], dtype=np.int)
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [25]:
np.argmax(a, axis=1)

array([3, 1, 1], dtype=int64)

In [26]:
np.argmin(a, axis=0)

array([0, 0, 2, 2], dtype=int64)