# 3-9 numpy - boolean & fancy Index

## boolean Index

In [1]:
import numpy as np

In [3]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array

array([1., 4., 0., 2., 3., 8., 9., 7.])

In [4]:
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [5]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [6]:
condition = test_array < 3
condition

array([ True, False,  True,  True, False, False, False, False])

In [7]:
test_array[condition]

array([1., 0., 2.])

In [11]:
A = np.array([
    [12, 13, 14, 12, 16, 14, 11, 10, 9],
    [11, 14, 12, 15, 10, 10, 11, 12, 11],
    [10, 12, 14, 12, 16, 14, 11, 12, 12],
    [9, 11, 14, 10, 10, 14, 11, 12, 10],
    [12, 11, 14, 12, 11, 14, 11, 12, 13],
    [10, 15, 12, 10, 12, 14, 11, 15, 12],
    [13, 17, 12, 15, 14, 14, 11, 18, 10],
    [10, 16, 12, 14, 15, 14, 11, 18, 11],
    [10, 19, 12, 18, 18, 14, 11, 17, 10],
    [10, 22, 12, 11, 11, 14, 11, 18, 13],
    [12, 17, 16, 12, 16, 14, 11, 17, 11]
])
A

array([[12, 13, 14, 12, 16, 14, 11, 10,  9],
       [11, 14, 12, 15, 10, 10, 11, 12, 11],
       [10, 12, 14, 12, 16, 14, 11, 12, 12],
       [ 9, 11, 14, 10, 10, 14, 11, 12, 10],
       [12, 11, 14, 12, 11, 14, 11, 12, 13],
       [10, 15, 12, 10, 12, 14, 11, 15, 12],
       [13, 17, 12, 15, 14, 14, 11, 18, 10],
       [10, 16, 12, 14, 15, 14, 11, 18, 11],
       [10, 19, 12, 18, 18, 14, 11, 17, 10],
       [10, 22, 12, 11, 11, 14, 11, 18, 13],
       [12, 17, 16, 12, 16, 14, 11, 17, 11]])

In [13]:
B = A < 15
B

array([[ True,  True,  True,  True, False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True, False,  True,  True,  True, False,  True],
       [ True, False,  True,  True, False,  True,  True, False,  True],
       [ True, False,  True, False, False,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False, False,  True, False,  True,  True, False,  True]])

In [14]:
B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 1, 0, 1, 1, 0, 1]])

## fancy Index

In [15]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)

In [16]:
a[b]

array([2., 2., 4., 8., 6., 4.])

In [17]:
a.take(b)  # take 함수 : bracket index와  같은 효과

array([2., 2., 4., 8., 6., 4.])

In [20]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b, c]   # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])