In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# ======== 파라미터 ========
training_steps = 22000
display_step = 1000

In [3]:
# ======== 학습데이터 ========
xy = np.loadtxt('train.txt', unpack=True, dtype='float32')

# 학습시간, 해외거주
x_data = xy[0:-1]

# 토익점수
y_data = xy[-1]

#  배열 위치 변환
X = x_data[:].T
print(X)
Y = y_data.reshape(-1,1)
print(Y)

[[54. 12.]
 [ 8.  0.]
 [30. 12.]
 [24. 15.]
 [46. 12.]
 [12.  0.]
 [20. 36.]
 [37. 12.]
 [40. 12.]
 [48. 24.]]
[[800.]
 [320.]
 [600.]
 [630.]
 [700.]
 [300.]
 [920.]
 [720.]
 [700.]
 [920.]]


In [4]:
# ======== W, B 초기값 설정 =========
#W = tf.Variable(tf.random.normal((2,1)))
#b = tf.Variable(np.random.randn(), name="bias")
W = tf.Variable(np.array([[0.1],[0.1]], dtype=np.float32))
b = tf.Variable(1.0)
W

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[0.1],
       [0.1]], dtype=float32)>

In [5]:
X

array([[54., 12.],
       [ 8.,  0.],
       [30., 12.],
       [24., 15.],
       [46., 12.],
       [12.,  0.],
       [20., 36.],
       [37., 12.],
       [40., 12.],
       [48., 24.]], dtype=float32)

In [6]:
W

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[0.1],
       [0.1]], dtype=float32)>

In [7]:
tf.matmul(X, W) + b

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[7.6000004],
       [1.8      ],
       [5.2      ],
       [4.9      ],
       [6.8      ],
       [2.2      ],
       [6.6000004],
       [5.9      ],
       [6.2      ],
       [8.200001 ]], dtype=float32)>

In [8]:
pred1 = tf.matmul(X, W) + b

In [9]:
pred1

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[7.6000004],
       [1.8      ],
       [5.2      ],
       [4.9      ],
       [6.8      ],
       [2.2      ],
       [6.6000004],
       [5.9      ],
       [6.2      ],
       [8.200001 ]], dtype=float32)>

In [10]:
Y

array([[800.],
       [320.],
       [600.],
       [630.],
       [700.],
       [300.],
       [920.],
       [720.],
       [700.],
       [920.]], dtype=float32)

In [11]:
pred1 - Y

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-792.4],
       [-318.2],
       [-594.8],
       [-625.1],
       [-693.2],
       [-297.8],
       [-913.4],
       [-714.1],
       [-693.8],
       [-911.8]], dtype=float32)>

In [12]:
tf.reduce_mean(tf.square(pred1 - Y)) 

<tf.Tensor: shape=(), dtype=float32, numpy=469987.3>

In [13]:
cost1 = tf.reduce_mean(tf.square(pred1 - Y)) 

In [14]:
cost1

<tf.Tensor: shape=(), dtype=float32, numpy=469987.3>

In [15]:
# ======== Multiple Linear Regression 에서 학습될 가설 ========
# Linear regression (Wx + b).
def linear_regression(X):
    return tf.matmul(X, W) + b

In [16]:
# ======== Multiple Linear Regression 에서 학습될 가설의 Cost Function ========
# Mean square error.
def mean_square(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred - y_true)) 

In [17]:
# ======== Gradient Descent Algorithm 에서 Step ========
learning_rate = 0.0006

In [18]:
# ======== 텐서플로우에 내장된 GradientDescentOptimizer ========
# Stochastic Gradient Descent Optimizer.
optimizer = tf.optimizers.SGD(learning_rate)

In [19]:
# ======== GradientDescentOptimizer ========
# Optimization process. 
def run_optimization():
    # Wrap computation inside a GradientTape for automatic differentiation. : 자동 미분
    with tf.GradientTape() as g:
        pred = linear_regression(X)
        cost = mean_square(pred, Y)

    # Compute gradients.
    # gradients = g.gradient(cost, [W, b])
    
    # Update W and b following gradients.
    # optimizer.apply_gradients(zip(gradients, [W, b]))
    
    weight, bias = g.gradient(cost, [W, b])
    #print("1. Weight: " ,weight)
    #print("2. Bais: " ,bias)

    W.assign_sub(learning_rate * weight)
    b.assign_sub(learning_rate * bias)

In [20]:
# Run training for the given number of steps.
for step in range(1, training_steps + 1):
    # Run the optimization to update W and b values.
    run_optimization()
    
    if step % display_step == 0:
        pred = linear_regression(X)
        cost = mean_square(pred, Y)
        print("step: %i, cost: %f, W1: %f, W2: %f, b: %f" % (step, cost, W[0].numpy(), W[1].numpy(), b.numpy()))
        #print("예측값 : {}".format(pred.numpy()))
        
        '''
        print("cost type: {}".format(type(cost)))
        print("W type: {}".format(type(W)))
        print("b type: {}".format(type(b)))
        print("pred type: {}".format(type(pred)))
        '''

step: 1000, cost: 6970.293945, W1: 10.868449, W2: 17.642492, b: 43.998299
step: 2000, cost: 4913.363770, W1: 10.142796, W2: 17.176504, b: 79.065842
step: 3000, cost: 3514.061035, W1: 9.544281, W2: 16.792160, b: 107.989395
step: 4000, cost: 2562.133789, W1: 9.050628, W2: 16.475155, b: 131.845398
step: 5000, cost: 1914.550415, W1: 8.643466, W2: 16.213688, b: 151.521683
step: 6000, cost: 1474.007446, W1: 8.307641, W2: 15.998034, b: 167.750610
step: 7000, cost: 1174.312744, W1: 8.030655, W2: 15.820164, b: 181.136093
step: 8000, cost: 970.432312, W1: 7.802197, W2: 15.673457, b: 192.176468
step: 9000, cost: 831.737000, W1: 7.613767, W2: 15.552454, b: 201.282425
step: 10000, cost: 737.386047, W1: 7.458352, W2: 15.452651, b: 208.792938
step: 11000, cost: 673.197388, W1: 7.330166, W2: 15.370335, b: 214.987625
step: 12000, cost: 629.532227, W1: 7.224438, W2: 15.302441, b: 220.096954
step: 13000, cost: 599.826294, W1: 7.137233, W2: 15.246441, b: 224.311142
step: 14000, cost: 579.617920, W1: 7.065

In [21]:
# ======== 학습된 우리의 프로그램에 예측 문의 ========

sample = np.array([
    [30, 10] 
], dtype=np.float32)

sample1 = np.array([
    [2, 24] 
], dtype=np.float32)

# 30 시간 공부하고 10개월 해외에서 거주했을 경우 토익점수 예측
print ("%i 시간, %i 개월 해외거주: %f 점" % (sample[0,0], sample[0,1], linear_regression(sample).numpy()))
print ("%i 시간, %i 개월 해외거주: %f 점" % (sample1[0,0], sample1[0,1], linear_regression(sample1).numpy()))

30 시간, 10 개월 해외거주: 594.916016 점
2 시간, 24 개월 해외거주: 614.948975 점
