In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# ======== 파라미터 ========
training_steps = 22000
display_step = 1000

In [3]:
# ======== 학습데이터 ========
# 학습시간, 해외거주
x_data = np.array( [
    [54, 8, 30, 24, 46, 12, 20, 37, 40, 48],  # 학습시간
    [12, 0, 12, 15, 12, 0, 36, 12, 12, 24]  # 해외거주
], dtype=np.float32)

# 토익점수
y_data = np.array([800, 320, 600, 630, 700, 680, 730, 720, 700, 920], dtype=np.float32)

#  배열 위치 변환
X = x_data[:].T
print(X)
Y = y_data.reshape(-1,1)
print(Y)

[[54. 12.]
 [ 8.  0.]
 [30. 12.]
 [24. 15.]
 [46. 12.]
 [12.  0.]
 [20. 36.]
 [37. 12.]
 [40. 12.]
 [48. 24.]]
[[800.]
 [320.]
 [600.]
 [630.]
 [700.]
 [680.]
 [730.]
 [720.]
 [700.]
 [920.]]


In [4]:
# ======== W, B 초기값 설정 =========
#W = tf.Variable(tf.random.normal((2,1)))
#b = tf.Variable(np.random.randn(), name="bias")
W = tf.Variable(np.array([[0.1],[0.1]], dtype=np.float32))
b = tf.Variable(1.0)
W

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[0.1],
       [0.1]], dtype=float32)>

In [5]:
X

array([[54., 12.],
       [ 8.,  0.],
       [30., 12.],
       [24., 15.],
       [46., 12.],
       [12.,  0.],
       [20., 36.],
       [37., 12.],
       [40., 12.],
       [48., 24.]], dtype=float32)

In [6]:
W

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[0.1],
       [0.1]], dtype=float32)>

In [7]:
tf.matmul(X, W) + b

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[7.6000004],
       [1.8      ],
       [5.2      ],
       [4.9      ],
       [6.8      ],
       [2.2      ],
       [6.6000004],
       [5.9      ],
       [6.2      ],
       [8.200001 ]], dtype=float32)>

In [8]:
pred1 = tf.matmul(X, W) + b

In [9]:
pred1

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[7.6000004],
       [1.8      ],
       [5.2      ],
       [4.9      ],
       [6.8      ],
       [2.2      ],
       [6.6000004],
       [5.9      ],
       [6.2      ],
       [8.200001 ]], dtype=float32)>

In [10]:
Y

array([[800.],
       [320.],
       [600.],
       [630.],
       [700.],
       [680.],
       [730.],
       [720.],
       [700.],
       [920.]], dtype=float32)

In [11]:
pred1 - Y

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-792.4],
       [-318.2],
       [-594.8],
       [-625.1],
       [-693.2],
       [-677.8],
       [-723.4],
       [-714.1],
       [-693.8],
       [-911.8]], dtype=float32)>

In [12]:
tf.reduce_mean(tf.square(pred1 - Y)) 

<tf.Tensor: shape=(), dtype=float32, numpy=475960.9>

In [13]:
cost1 = tf.reduce_mean(tf.square(pred1 - Y)) 

In [14]:
cost1

<tf.Tensor: shape=(), dtype=float32, numpy=475960.9>

In [15]:
# ======== Multiple Linear Regression 에서 학습될 가설 ========
# Linear regression (Wx + b).
def linear_regression(X):
    return tf.matmul(X, W) + b

In [16]:
# ======== Multiple Linear Regression 에서 학습될 가설의 Cost Function ========
# Mean square error.
def mean_square(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred - y_true)) 

In [17]:
# ======== Gradient Descent Algorithm 에서 Step ========
learning_rate = 0.0006

In [18]:
# ======== 텐서플로우에 내장된 GradientDescentOptimizer ========
# Stochastic Gradient Descent Optimizer.
optimizer = tf.optimizers.SGD(learning_rate)

In [19]:
# ======== GradientDescentOptimizer ========
# Optimization process. 
def run_optimization():
    # Wrap computation inside a GradientTape for automatic differentiation. : 자동 미분
    with tf.GradientTape() as g:
        pred = linear_regression(X)
        cost = mean_square(pred, Y)

    # Compute gradients.
    # gradients = g.gradient(cost, [W, b])
    
    # Update W and b following gradients.
    # optimizer.apply_gradients(zip(gradients, [W, b]))
    
    weight, bias = g.gradient(cost, [W, b])
    #print("1. Weight: " ,weight)
    #print("2. Bais: " ,bias)
    
    W.assign_sub(learning_rate * weight)
    b.assign_sub(learning_rate * bias)

In [20]:
# Run training for the given number of steps.
for step in range(1, training_steps + 1):
    # Run the optimization to update W and b values.
    run_optimization()
    
    if step % display_step == 0:
        pred = linear_regression(X)
        cost = mean_square(pred, Y)
        print("step: %i, cost: %f, W1: %f, W2: %f, b: %f" % (step, cost, W[0].numpy(), W[1].numpy(), b.numpy()))
        #print("예측값 : {}".format(pred.numpy()))
        
        '''
        print("cost type: {}".format(type(cost)))
        print("W type: {}".format(type(W)))
        print("b type: {}".format(type(b)))
        print("pred type: {}".format(type(pred)))
        '''

step: 1000, cost: 25434.839844, W1: 12.987769, W2: 10.282816, b: 72.890022
step: 2000, cost: 19626.621094, W1: 11.768386, W2: 9.499773, b: 131.817352
step: 3000, cost: 15675.356445, W1: 10.762645, W2: 8.853922, b: 180.420380
step: 4000, cost: 12987.370117, W1: 9.933115, W2: 8.321228, b: 220.507812
step: 5000, cost: 11158.762695, W1: 9.248921, W2: 7.881864, b: 253.571823
step: 6000, cost: 9914.785156, W1: 8.684603, W2: 7.519478, b: 280.842834
step: 7000, cost: 9068.521484, W1: 8.219154, W2: 7.220584, b: 303.335876
step: 8000, cost: 8492.819336, W1: 7.835254, W2: 6.974057, b: 321.888062
step: 9000, cost: 8101.177246, W1: 7.518616, W2: 6.770725, b: 337.189697
step: 10000, cost: 7834.747070, W1: 7.257454, W2: 6.603015, b: 349.810577
step: 11000, cost: 7653.497559, W1: 7.042048, W2: 6.464690, b: 360.220123
step: 12000, cost: 7530.196777, W1: 6.864385, W2: 6.350600, b: 368.805817
step: 13000, cost: 7446.317383, W1: 6.717846, W2: 6.256498, b: 375.887329
step: 14000, cost: 7389.252441, W1: 6.5

In [21]:
# ======== 학습된 우리의 프로그램에 예측 문의 ========

sample = np.array([
    [30, 10] 
], dtype=np.float32)

sample1 = np.array([
    [2, 24] 
], dtype=np.float32)

# 30 시간 공부하고 10개월 해외에서 거주했을 경우 토익점수 예측
print ("%i 시간, %i 개월 해외거주: %f 점" % (sample[0,0], sample[0,1], linear_regression(sample).numpy()))
# 2 시간 공부하고 24개월 해외에서 거주했을 경우 토익점수 예측
print ("%i 시간, %i 개월 해외거주: %f 점" % (sample1[0,0], sample1[0,1], linear_regression(sample1).numpy()))

30 시간, 10 개월 해외거주: 646.748779 점
2 시간, 24 개월 해외거주: 557.037109 점
