In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# ======== 파라미터 ========
training_steps = 22000
display_step = 1000

In [7]:
# ======== 학습데이터 ========
xy = np.loadtxt('softmax_data.txt', unpack=True, dtype='float32')

# 학습시간, 해외거주(월)
x_data = xy[0:2]

# 영어 학점 : 0 : A, 1: B , 2: C, 3: D
y_data = xy[2:]

#  배열 위치 변환
X = x_data[:].T
print(X)
Y = y_data.T
print(Y)

[[54. 12.]
 [ 8.  0.]
 [30. 12.]
 [24. 15.]
 [46. 12.]
 [12.  0.]
 [20. 36.]
 [37. 12.]
 [40. 12.]
 [48. 24.]]
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


In [8]:
# ======== W, B 초기값 설정 =========
#W = tf.Variable(tf.random.normal((2,1)))
#b = tf.Variable(np.random.randn(), name="bias")
W = tf.Variable(tf.zeros([2, 4]))
b = tf.Variable(1.0)
W

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [9]:
X

array([[54., 12.],
       [ 8.,  0.],
       [30., 12.],
       [24., 15.],
       [46., 12.],
       [12.,  0.],
       [20., 36.],
       [37., 12.],
       [40., 12.],
       [48., 24.]], dtype=float32)

In [10]:
W

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [11]:
tf.matmul(X, W) + b

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [12]:
hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)

In [13]:
hypothesis

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]], dtype=float32)>

In [14]:
# ======== logistic Regression 에서 학습될 가설 ========
# Logistic regression (Wx + b).
def logistic_regression(x):
    # Apply softmax to normalize the logits to a probability distribution.
    return tf.nn.softmax(tf.matmul(x, W) + b)

In [15]:
# ======== logistic Regression 에서 학습될 가설의 Cost Function ========
# Cross-Entropy loss function.
def cross_entropy(y_pred, y_true):
    # Clip prediction values to avoid log(0) error.
    y_pred = tf.clip_by_value(y_pred, 1e-9, 1.)
    # Compute cross-entropy.
    return tf.reduce_mean(-tf.reduce_sum(y_true * tf.math.log(y_pred)))

In [57]:
# ======== logistic Regression 에서 학습될 가설의 정확도 ========
# Accuracy metric.
def accuracy(y_pred, y_true):
    # Predicted class is the index of highest score in prediction vector (i.e. argmax).    
    #correct_prediction = tf.equal(tf.argmax(y_pred), tf.cast(y_true, tf.int64))
    correct_prediction = tf.equal(tf.argmax(y_pred,1), tf.cast(tf.argmax(y_true,1), tf.int64))
    return tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [58]:
pred = logistic_regression(X)
pred

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[1.6116926e-04, 9.7233433e-01, 2.4560453e-02, 2.9440953e-03],
       [3.6819370e-06, 1.7326104e-02, 1.3216116e-05, 9.8265702e-01],
       [2.3282214e-01, 1.3479804e-08, 7.6717782e-01, 2.2372612e-16],
       [6.6062069e-01, 3.7646491e-16, 3.3937931e-01, 7.7874670e-29],
       [2.2352900e-02, 2.8657768e-02, 9.4898778e-01, 1.5299511e-06],
       [7.2359536e-09, 2.3357859e-03, 4.9208190e-08, 9.9766421e-01],
       [9.9950230e-01, 0.0000000e+00, 4.9763761e-04, 0.0000000e+00],
       [9.0240560e-02, 8.5429474e-06, 9.0975088e-01, 4.8543379e-12],
       [5.7862677e-02, 1.3056846e-04, 9.4200677e-01, 3.3728598e-10],
       [3.8511446e-01, 3.9992038e-21, 6.1488557e-01, 0.0000000e+00]],
      dtype=float32)>

In [59]:
tf.argmax(pred,1)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([1, 3, 2, 0, 2, 3, 0, 2, 2, 2], dtype=int64)>

In [60]:
tf.argmax(Y,1)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([1, 3, 2, 2, 2, 3, 0, 2, 2, 0], dtype=int64)>

In [61]:
tf.cast(Y, tf.int64)

<tf.Tensor: shape=(10, 4), dtype=int64, numpy=
array([[0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0]], dtype=int64)>

In [62]:
tf.equal(tf.argmax(pred,1), tf.cast(tf.argmax(Y,1), tf.int64))

<tf.Tensor: shape=(10,), dtype=bool, numpy=
array([ True,  True,  True, False,  True,  True,  True,  True,  True,
       False])>

In [63]:
# ======== Gradient Descent Algorithm 에서 Step ========
learning_rate = 0.0006

In [64]:
# ======== 텐서플로우에 내장된 GradientDescentOptimizer ========
# Stochastic Gradient Descent Optimizer.
optimizer = tf.optimizers.SGD(learning_rate)

In [65]:
# ======== GradientDescentOptimizer ========
# Optimization process. 
def run_optimization(x, y):
    # Wrap computation inside a GradientTape for automatic differentiation.
    with tf.GradientTape() as g:
        pred = logistic_regression(x)
        loss = cross_entropy(pred, y)

    # Compute gradients.
    gradients = g.gradient(loss, [W, b])
    
    # Update W and b following gradients.
    optimizer.apply_gradients(zip(gradients, [W, b]))

In [66]:
# Run training for the given number of steps.
for step in range(1, training_steps + 1):
    # Run the optimization to update W and b values.
    run_optimization(X, Y)

    if step % display_step == 0:
        pred = logistic_regression(X)
        loss = cross_entropy(pred, Y)
        acc = accuracy(pred, Y)
        print("step: %i, loss: %f, accuracy: %f" % (step, loss, acc))
        #print("step: %i, loss: %f" % (step, loss))
        
        '''
        print("cost type: {}".format(type(cost)))
        print("W type: {}".format(type(W)))
        print("b type: {}".format(type(b)))
        print("pred type: {}".format(type(pred)))
        '''

step: 1000, loss: 2.553336, accuracy: 0.800000
step: 2000, loss: 2.551781, accuracy: 0.800000
step: 3000, loss: 2.550288, accuracy: 0.800000
step: 4000, loss: 2.548855, accuracy: 0.800000
step: 5000, loss: 2.547474, accuracy: 0.800000
step: 6000, loss: 2.546142, accuracy: 0.800000
step: 7000, loss: 2.544870, accuracy: 0.800000
step: 8000, loss: 2.543639, accuracy: 0.800000
step: 9000, loss: 2.542453, accuracy: 0.800000
step: 10000, loss: 2.541309, accuracy: 0.800000
step: 11000, loss: 2.540206, accuracy: 0.800000
step: 12000, loss: 2.539138, accuracy: 0.800000
step: 13000, loss: 2.538107, accuracy: 0.800000
step: 14000, loss: 2.537115, accuracy: 0.800000
step: 15000, loss: 2.536148, accuracy: 0.800000
step: 16000, loss: 2.535210, accuracy: 0.800000
step: 17000, loss: 2.534309, accuracy: 0.800000
step: 18000, loss: 2.533437, accuracy: 0.800000
step: 19000, loss: 2.532585, accuracy: 0.800000
step: 20000, loss: 2.531758, accuracy: 0.800000
step: 21000, loss: 2.530962, accuracy: 0.800000
s

In [85]:
# ======== 학습된 우리의 프로그램에 예측 문의 ========
sample = np.array([
    [30, 10] 
], dtype=np.float32)

dict = {
    0 : "A",
    1 : "B",
    2 : "C",
    3 : "D"
}

# 30 시간 공부하고 10개월 해외에서 거주했을 경우 영어학점 예측
predictions = logistic_regression(sample)
result = np.argmax(predictions.numpy())
print ("%i 시간, %i 개월 해외거주: %s " % (sample[0,0], sample[0,1], dict[result]))

30 시간, 10 개월 해외거주: C 
